### ISSUE TITLE
Original gossip data have 22.8k articles but only 6k in yours?

### ISSUE THREAD

**Issue by CodingLL** [ICTMCG/ARG#3]
In FakeNewsNet, we have to manually download the articles. Originally, there were 22.8k data, but only 6k are present in your repository. I also tried to download them, but about 1/3 of the URLs failed. Can you provide some details on how to implement the dataset? Thanks!

**Comment by beanandrew** [comment]
As we report in our paper, "we preprocess the datasets with deduplication and temporal data split to avoid possible performance overrating led by data leakage for the SLM.". To get the processed dataset, you can fill in and submit the application form.
